<select class="chosen-select" id="selectUser" onchange="getAddressUser(this)">
    <option value="">all</option>
    <?php 
    foreach ($users as $user) {
        print_r("<option value='{$user->email}'> {$user->email} </option>");
    }
    ?>
</select>;

<p id="forExperement"> Experement </p>

    <table class="table table-bordered table-hover">
        <thead class="thead-light">
            <tr>
                <th>City</th>
                <th>Region</th>
                <th>Street</th>
                <th>Postcode</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody id="parentBody">
        </tbody>
    </table>
